export const LANE_MARKER: string;
export const ORPHAN_SHELL_AGE_MS: number;
export type ProcessRow = { pid: number; ppid: number; ageMs?: number; createdAt?: string; line: string };
export function elapsedMs(etime: string): number | undefined;
export function parseProcessTable(text: string): ProcessRow[];
export function parseWindowsProcessTable(text: string | unknown): ProcessRow[];
export function readProcessTable(options?: ((args: string[]) => Promise<{ stdout: string }>) | { platform?: string; run?: (args: string[]) => Promise<{ stdout: string }>; runPowerShell?: (script: string) => Promise<string> }): Promise<ProcessRow[]>;
export function laneProcesses(rows: ProcessRow[], intentPath: string | undefined, options?: { self?: number; recordedProcesses?: { pid: number; createdAt: string }[] }): ProcessRow[];
export function killLaneProcesses(input: {
  intentPath?: string;
  recordedProcesses?: { pid: number; createdAt: string }[];
  expectedPids?: number[];
  platform?: string;
  table?: () => Promise<ProcessRow[]>;
  kill?: (pid: number, signal: string) => unknown;
  runPowerShell?: (script: string) => Promise<string>;
  graceMs?: number;
  delay?: (ms: number) => Promise<unknown>;
}): Promise<{ signalled: Array<{ pid: number; command: string }>; killed: number[]; survivors: number[] }>;
export function portListening(port: number, options?: { timeoutMs?: number }): Promise<boolean>;
export function busyPorts(ports: number[] | undefined, listening?: (port: number) => Promise<boolean>): Promise<number[]>;
export function orphanShells(rows: ProcessRow[], options?: { minAgeMs?: number }): Array<{ pid: number; ageMs?: number; command: string }>;
